// chatbot/angular/src/app/inspector/inspector.component.ts
/*! JointJS+ v4.2.2 (2026-01-22) - HTML5 Diagramming Framework

Copyright (c) 2025 client IO

This Source Code Form is subject to the terms of the JointJS+
License, v. 2.0. If a copy of the JointJS+ License was not
distributed with this file, You can obtain one at
https://www.jointjs.com/license or from the JointJS+ archive as was
distributed by client IO. See the LICENSE file.
*/

import type {
    OnDestroy,
    OnInit
} from '@angular/core';
import {
    Component
} from '@angular/core';
import { Subscription } from 'rxjs';
import type { dia } from '@joint/plus';

import type { EventBusService } from '../../services/event-bus.service';
import { ShapeTypesEnum } from '../../joint-plus/shapes/app.shapes';
import { SharedEvents } from '../../joint-plus/controller';


@Component({
    selector: 'chatbot-inspector',
    templateUrl: './inspector.component.html',
    styleUrls: ['./inspector.component.scss']
})
export class InspectorComponent implements OnInit, OnDestroy {

    public cell: dia.Cell;
    public subscriptions = new Subscription();
    public shapeTypesEnum = ShapeTypesEnum;

    constructor(private readonly eventBusService: EventBusService) {
    }

    public ngOnInit(): void {
        this.subscriptions.add(
            this.eventBusService.subscribe(SharedEvents.SELECTION_CHANGED, (selection: dia.Cell[]) => this.setCell(selection))
        );
    }

    private setCell(selection: dia.Cell[]): void {
        const [cell = null] = selection;
        this.cell = cell;
    }

    public ngOnDestroy(): void {
        this.subscriptions.unsubscribe();
    }
}

// chatbot/react-ts/src/components/Chatbot/Inspector/Inspector.tsx
import type { ReactElement } from 'react';
import React, { useContext, useEffect, useState } from 'react';
import type { dia, shapes } from '@joint/plus';
import { Subscription } from 'rxjs';

import MessageInspector from './MessageInspector';
import './Inspector.scss';
import LinkInspector from './LinkInspector';
import LabelInspector from './LabelInspector';
import eventBusServiceContext from '../../../services/event-bus-service.context';
import { SharedEvents } from '../../../joint-plus/controller';
import { ShapeTypesEnum } from '../../../joint-plus/shapes/app.shapes';

const Inspector = (): ReactElement => {
    const [cell, setCell] = useState<dia.Cell>(null);
    const [subscriptions] = useState(new Subscription());
    const eventBusService = useContext(eventBusServiceContext);

    const setSelection = (selection: dia.Cell[]): void => {
        const [selectedCell = null] = selection;
        setCell(selectedCell);
    };

    useEffect(() => {
        subscriptions.add(
            eventBusService.subscribe(SharedEvents.SELECTION_CHANGED, (selection: dia.Cell[]) => setSelection(selection))
        );
        return () => {
            subscriptions.unsubscribe();
        };
    }, [eventBusService, subscriptions]);

    const chooseInspector = (): ReactElement => {
        switch (cell.get('type')) {
            case ShapeTypesEnum.MESSAGE:
                return <MessageInspector cell={cell as shapes.app.Message}/>;
            case ShapeTypesEnum.LINK:
                return <LinkInspector cell={cell as dia.Link}/>;
            case ShapeTypesEnum.FLOWCHART_START:
                return <LabelInspector cell={cell}/>;
            case ShapeTypesEnum.FLOWCHART_END:
                return <LabelInspector cell={cell}/>;
            default:
                return;
        }
    };

    const emptyInspector = (): ReactElement => {
        return (
            <>
                <h1>Component</h1>
                <label htmlFor="label">Label</label>
                <input disabled id="label"/>
            </>
        );
    };

    return (
        <div className={'chatbot-inspector ' + (!cell ? 'disabled-chatbot-inspector' : '')}>
            {
                cell ? chooseInspector() : emptyInspector()
            }
        </div>
    );
};

export default Inspector;
