// chatbot/angular/src/app/json-editor/json-editor.component.ts
/*! JointJS+ v4.2.2 (2026-01-22) - HTML5 Diagramming Framework

Copyright (c) 2025 client IO

This Source Code Form is subject to the terms of the JointJS+
License, v. 2.0. If a copy of the JointJS+ License was not
distributed with this file, You can obtain one at
https://www.jointjs.com/license or from the JointJS+ archive as was
distributed by client IO. See the LICENSE file.
*/

import type { OnInit } from '@angular/core';
import { Component, Input } from '@angular/core';
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';

import type { EventBusService } from '../../services/event-bus.service';
import { SharedEvents } from '../../joint-plus/controller';

const DEBOUNCE_TIME_MS = 500;

@Component({
    selector: 'chatbot-json-editor',
    templateUrl: './json-editor.component.html',
    styleUrls: ['./json-editor.component.scss']
})
export class JsonEditorComponent implements OnInit {

    @Input() content: object;
    public placeholder = 'e.g. { "cells": [{ "type": "app.Message"}] }';
    public contentSubject = new Subject<object>();

    constructor(private eventBusService: EventBusService) {
    }

    public ngOnInit(): void {
        const { contentSubject, eventBusService } = this;
        contentSubject.pipe(debounceTime(DEBOUNCE_TIME_MS)).subscribe((json: object) => {
            eventBusService.emit(SharedEvents.JSON_EDITOR_CHANGED, json);
        });
    }

    public parseJSON(jsonString: string): void {
        const { contentSubject } = this;
        let json;
        if (!jsonString) {
            json = { cells: [] };
        } else {
            try {
                json = JSON.parse(jsonString);
            } catch {
                // Invalid JSON
                return;
            }
        }
        contentSubject.next(json);
    }
}

// chatbot/react-redux-ts/src/components/Chatbot/JsonEditor/JsonEditor.tsx
import type { ReactElement } from 'react';
import React, { useEffect, useState } from 'react';
import { useDispatch } from 'react-redux';
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';

import './JsonEditor.scss';
import { SharedEvents } from '../../../joint-plus/controller';
import { actionCreator } from '../../../redux/helpers/actionCreator';

interface Props {
    content: object;
}

const DEBOUNCE_TIME_MS = 500;

const JsonEditor = (props: Props): ReactElement => {

    const [placeholder] = useState('e.g. { "cells": [{ "type": "app.Message"}] }');
    const [content, setContent] = useState<string | object>(null);
    const [contentSubject] = useState(new Subject<object>());

    const dispatch = useDispatch();

    useEffect(() => {
        contentSubject.pipe(debounceTime(DEBOUNCE_TIME_MS)).subscribe((json: object) => {
            dispatch(
                actionCreator(SharedEvents.JSON_EDITOR_CHANGED, json)
            );
        });
    }, [dispatch, contentSubject]);

    useEffect(() => {
        if (props.content) {
            setContent(props.content);
        }
    }, [props.content]);

    const parseJSON = (jsonString: string): void => {
        setContent(jsonString);
        let json;
        if (!jsonString) {
            json = { cells: [] };
        } else {
            try {
                json = JSON.parse(jsonString);
            } catch (e) {
                // Invalid JSON
                return;
            }
        }
        contentSubject.next(json);
    };

    const formatJSON = (json: string | object): string => {
        if (!json) {
            return '';
        }
        return typeof json === 'string' ? json : JSON.stringify(json, null, 2);
    };

    return (
        <div className="chatbot-json-editor">
            <textarea placeholder={placeholder}
                spellCheck="false"
                value={formatJSON(content)}
                onChange={(e) => parseJSON(e.target.value)}
            />
        </div>
    );
};

export default JsonEditor;
